### ISSUE TITLE
Fix the '../../..config' issue

### ISSUE THREAD

**Issue by cbacon91** [cbacon91/DiscordNameGen#5]
Right now lines like this exist: `const config = require('../../config'); //todo let's stop using ../../`

There should be a cleaner way to write this - investigate using `import` or some other form of cleaner injection.

**Comment by rizowski** [comment]
@cbacon91 You can use https://www.npmjs.com/package/config for cleaning up `../../` for config but you are going to see `../../` regardless of `import` or `require` since they both look at relative paths. You could avoid it by putting every file in the same directory but that can get a little wild.

**Comment by cbacon91** [comment]
The real issue I didn't like is that many of my files had / have something like 

`const someModule = require('../../../Dir1/Dir2/SomeModule')`

The core issue is that I didn't like having to specify the filepath - it seemed like poor design. You could argue I shouldn't be referencing files from that far away, but if I had some common functions (ie, my own version of a lodash-type library), I would still want to use them but keep them near the root dir. 

The package you referenced would fix this for config, but for other modules I would still be boned. For some reason, I thought `import` didn't use relative paths, but that was wrong. 

I've fixed a lot of this by just moving files around, but I'm still a bit unhappy with where I left off and don't have a long-term solution.
